# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agency-extensions/tfnsw-vehicle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agency-extensions/tfnsw-vehicle.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%agency-extensions/tfnsw-vehicle.proto\"Y\n\x16TfnswVehicleDescriptor\x12\x1d\n\x0f\x61ir_conditioned\x18\x01 \x01(\x08:\x04true\x12 \n\x15wheelchair_accessible\x18\x02 \x01(\x05:\x01\x30'
)




_TFNSWVEHICLEDESCRIPTOR = _descriptor.Descriptor(
  name='TfnswVehicleDescriptor',
  full_name='TfnswVehicleDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='air_conditioned', full_name='TfnswVehicleDescriptor.air_conditioned', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wheelchair_accessible', full_name='TfnswVehicleDescriptor.wheelchair_accessible', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['TfnswVehicleDescriptor'] = _TFNSWVEHICLEDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TfnswVehicleDescriptor = _reflection.GeneratedProtocolMessageType('TfnswVehicleDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _TFNSWVEHICLEDESCRIPTOR,
  '__module__' : 'agency_extensions.tfnsw_vehicle_pb2'
  # @@protoc_insertion_point(class_scope:TfnswVehicleDescriptor)
  })
_sym_db.RegisterMessage(TfnswVehicleDescriptor)


# @@protoc_insertion_point(module_scope)
